pipeline {
  agent any
  stages {
    stage('Prepare') {
      steps {
        echo 'Preparation Started'
        git(url: 'https://github.com/timyshark/academy-ng', branch: 'app-alpha-001')
        bat(script: 'npm --version', label: 'Node JS Version')
        bat(script: 'cd academy-ng', label: 'move into folder')
        bat 'npm install'
        bat 'ng build'
      }
    }

    stage('Build') {
      steps {
        bat(script: 'ng build', label: 'Building Academy Vue')
      }
    }

  }
}