pipeline {
  agent any
  stages {
    stage('Preparation pipeline') {
      steps {
        echo 'Preparing Academy Vu'
        git(url: 'https://github.com/timyshark/academy-ng.git', branch: 'app-alpha-001')
      }
    }
    stage('Unit Test') {
      steps {
        echo 'Unit Testing started'

      }
    }
   stage('E2E Test') {
      steps {
        echo 'E2E Testing started'
      }
    }
    stage('Build') {
      steps {
        echo 'Building started'
      }
    }
   stage('Deploy') {
      steps {
        echo 'Deploying started'
      }
    }
  stage('Cleanup') {
      steps {
        echo 'Deploying started'
      }
    }
  }
}