pipeline {
  agent any
  stages {
    stage('Prepare') {
      steps {
        echo 'Preparation Started'
        sh 'npm --version'
        git(url: 'https://github.com/timyshark/academy-ng', branch: 'app-alpha-001')
      }
    }

  }
}